.TH NOVENA-INSTALL-SPL 8 "11 Oct 2014" Novena "Linux System Administration"
.SH NAME
novena-install-spl \- install U-Boot SPL file to disk image
.SH SYNOPSIS
.B novena-install-spl
.RB [\| root-device \|]
.RB [[\| path-to-spl \|]]

.SH DESCRIPTION
.LP
U-Boot requires a Secondary Program Loader to configure memory timings and
to load u-boot.img off of the disk.  The SPL file must be located at offset
1024 from the start of the disk.  
.B novena-install-spl
can install the SPL file to the start of the disk.
.SH OPTIONS
.TP
.B root-device
Path to the root device.  If connected via MMC, likely /dev/mmcblk0 or
/dev/mmcblk1.  If connected via USB or STA, likely /dev/sda
.TP
.B path-to-spl
Full path to the SPL file.  If unspecified, will default to /boot/u-boot.spl
.SH AUTHORS
Written by Sean Cross <xobs@kosagi.com>
