#!/bin/sh
set -e

files="u-boot.spl u-boot.img"
pkg=u-boot-novena

if [ "$1" = configure ] ; then
	for file in ${files}
	do
                cp /usr/share/${pkg}/${file} /boot/${file}
	done

	if grep -q root=PARTUUID=4e6f7653-03 /proc/cmdline
	then
		/usr/sbin/novena-install-spl
	fi

	if grep -q root=PARTUUID=4e6f764d-03 /proc/cmdline
	then
		/usr/sbin/novena-install-spl
	fi
fi
#DEBHELPER#
exit 0
